/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

import javax.swing.JPanel;

/**
 *
 * @author david
 */
public class modificar extends javax.swing.JPanel {

    /**
     * Creates new form modificar
     */
    public modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModificarr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelModificarr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelModificarr.setMinimumSize(new java.awt.Dimension(774, 410));
        panelModificarr.setPreferredSize(new java.awt.Dimension(774, 484));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Modificar");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarrLayout = new javax.swing.GroupLayout(panelModificarr);
        panelModificarr.setLayout(panelModificarrLayout);
        panelModificarrLayout.setHorizontalGroup(
            panelModificarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarrLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1))
            .addGroup(panelModificarrLayout.createSequentialGroup()
                .addGap(588, 588, 588)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelModificarrLayout.setVerticalGroup(
            panelModificarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarrLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(302, 302, 302)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(panelModificarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        principal p1 = new principal();
        showPanel3(p1.getFondo2());

    }//GEN-LAST:event_jButton1ActionPerformed
public JPanel getFondo3() {
        return panelModificarr;
    }
private void showPanel3(JPanel p){
        p.setSize(1150, 694);
        p.setLocation(0, 0);
        panelModificarr.removeAll();
        panelModificarr.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        panelModificarr.revalidate();
        panelModificarr.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelModificarr;
    // End of variables declaration//GEN-END:variables
}
